-- ============================================
-- Agregar tipos de notificación faltantes al enum ClientNotificationType
-- ============================================
-- Agrega PAYMENT_UPDATED, PAYMENT_DELETED,
-- CONTRACT_CANCELLATION_REQUESTED_BY_STUDIO, CONTRACT_CANCELLATION_CONFIRMED,
-- CONTRACT_CANCELLATION_REJECTED

ALTER TYPE "ClientNotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_UPDATED';
ALTER TYPE "ClientNotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_DELETED';
ALTER TYPE "ClientNotificationType" ADD VALUE IF NOT EXISTS 'CONTRACT_CANCELLATION_REQUESTED_BY_STUDIO';
ALTER TYPE "ClientNotificationType" ADD VALUE IF NOT EXISTS 'CONTRACT_CANCELLATION_CONFIRMED';
ALTER TYPE "ClientNotificationType" ADD VALUE IF NOT EXISTS 'CONTRACT_CANCELLATION_REJECTED';

